server:
  port: 8081
spring:
  rabbitmq:
    host: 114.116.121.100
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  data:
    mongodb:
      database: yuan-server
      host: 114.116.121.100
      username:
      password:
      port: 27017
      uri: mongodb://114.116.121.100:27017/yuan-server